designs: {}
proposals:
  2026-09-15-rename-to-fstdd: proposals/2026-09-15-rename-to-fstdd.yaml
specs:
  agent:
    2026-09-15-rename-to-fstdd: specs/agent/2026-09-15-rename-to-fstdd.yaml
  code:
    2026-09-15-rename-to-fstdd: specs/code/2026-09-15-rename-to-fstdd.yaml
version: '2.9'
