designs: {}
proposals:
  2026-09-15-crlf-eol-governance: proposals/2026-09-15-crlf-eol-governance.yaml
  2026-09-25-new-isolate-flag: proposals/2026-09-25-new-isolate-flag.yaml
  2026-10-03-caveman-kg-sync: proposals/2026-10-03-caveman-kg-sync.yaml
specs:
  agent:
    2026-09-25-new-isolate-flag: specs/agent/2026-09-25-new-isolate-flag.yaml
  code:
    2026-09-25-new-isolate-flag: specs/code/2026-09-25-new-isolate-flag.yaml
    2026-10-03-caveman-kg-sync-caveman-compressor: specs/code/2026-10-03-caveman-kg-sync-caveman-compressor.yaml
    2026-10-03-caveman-kg-sync-kg-autosync: specs/code/2026-10-03-caveman-kg-sync-kg-autosync.yaml
version: '2.9'
